### ISSUE TITLE
Cannot Gut Animals

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#133]
Using the actionKeyHandler at the hunting grounds doesn't gut the animals.

**Comment by Jawshy** [comment]
The guy testing with me managed to gut a sheep and goat. He said that he had to spam the Interaction Key (Left Windows Key) until his character started gutting the animal. One the second attempt I asked him to cancel the action and try again at which point he managed to gut on first key press. 

Same thing happens when trying to catch a turtle. Once you have killed the turtle it is a nuisance to try to get the sweet spot to catch it/put into in virutal 'Y' inventory.

**Comment by tkcjesse** [comment]
Mmm. Okay. May do nearest objects then or something.

**Comment by tkcjesse** [comment]
If you have time.  Could you possibly test if you're able to access your home crate Arma inventory?

**Comment by NiiRoZz** [comment]
I will fix it just let me time of 2 hours for test ect ..

**Comment by Jawshy** [comment]
@tkcjesse, I can access my house's inventory, both physical and virtual. However, I sync'ed data, logged out of the server, reconnected, and I've lost the keys to my house.

**Comment by NiiRoZz** [comment]
Fixed, if you test you need to cursor anything and not the animal because if i script for look animal create more De-Sync
