### ISSUE TITLE
opinion : About Commit 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#451]
thanks for your commit and patch to this repository contributor..

but im disappointing sometimes. 

everyday i fetched from this master repository and applied on my server and play about 40~50 people.  but sometimes i found some of errors of patched files / codes, so i wasted lots of time. 

why don't every-commiter do TEST  on lastest master before pull request or commit???

**Comment by Liam0** [comment]
I think everyone is trying to keep it at a minimum @HyunsukBaek but sometimes u get blind sided by the code and errors happen. i think everyone is commited to get the problems solved as fast a posible tho (when they do happen).

i like making my changes as pull requests because this way u have a second pair of eyes looking trough the code just before it gets merged.

**Comment by Jawshy** [comment]
Also keep in mind that as this is a development repository it will not necessarily always be stable. 

Think of ArmaLife/Altis like *Arma 3*'s [dev-branch](https://dev.arma3.com/dev-branch) and [TAWTonic/Altis-Life](https://github.com/TAWTonic/Altis-Life) like *Arma 3*'s [main branch](https://dev.arma3.com/spotrep).

**Comment by danielstuart14** [comment]
Master branch for daily use is the same as using a plastic bag as condom.... YOU KNOW IT WASN'T MAKE FOR THAT.

If you use a build in your server, or you use the latest version in Tonic's repo, or, you use the latest release here. (But it can have bugs too)
