### ISSUE TITLE
Auction House  [suggestion]

### ISSUE THREAD

**Issue by Smacks1337** [ArmaLife/Altis#472]
Would it be possible to include this Auction House for 4.4r2 ?
Here is a tutorial here for 3.1.4.8 and 4.4, but i think it would make an awesome default feature.

http://www.altisliferpg.com/topic/13692-release-auction-house-v1-by-fresqo/?page=1

**Comment by tkcjesse** [comment]
Would just like to note the following:
It seems there are some author crediting issues there. - http://www.altisliferpg.com/topic/13692-release-auction-house-v1-by-fresqo/?do=findComment&comment=85452

Also, seems to be based off a purchased script or something?

**Comment by clackd1amond** [comment]
Yes, it does. And I don't think this should be in the basic framework. Cause this is basic, ya know :)

**Comment by tkcjesse** [comment]
Yeah. My opinion on the matter is simply that it shouldn't be added. Just because as already stated this is meant to be basic. If people want to add that they can. Shouldn't force something like that on people. Some people want trading systems, some want crafting systems, and some want both. Some want something else completely different. Leave it to them to decide.

**Comment by DarkSilencerZA** [comment]
Well you can always just add it with the option to disable it via the Config_Master.hpp just life everything else. Otherwise you might as well say the same thing for the Headless client? I suppose if we just add everything here, people will just get everything done for them and have a working server without having to do anything, but then that's just being selfish. Tough decision.

**Comment by setoy** [comment]
I'm with @Smacks1337 and @DarkSilencerZA at this point. Providing a framework with a ton of addons would allow to just "user-friendly" enable and disable all those addons in the config file and have a smooth working server.

**Comment by sargken** [comment]
I disagree with that because the server owner has to customize it the way he wants, with the addition of all this extra content that they may never use will add on extra file size.

**Comment by devShit** [comment]
but i tink we got many system with extra file size and its optional already
