### ISSUE TITLE
Slot number is wrong.

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#487]
i applied patch 015f267be434907aa3f6e2322689e4d1538c2ea4, and then 

when i join to select role display ( cop, medic, civ selection ) in my channel,

cop, medic, civ group starts from ECHO 1-1 NOT alpha 1-1, and 
blank first slot of medic and cop, spam log as follows. 

Group B Alpha 1-2 (0x49082c00) - network ID 2:1306
 - no leader
Group B Alpha 1-2 (0x49082c00) - network ID 2:1306
 - no leader
Group B Alpha 1-2 (0x49082c00) - network ID 2:1306

**Comment by tkcjesse** [comment]
? There is nothing wrong with slot numbers.

This has always been an issue. It's due to how groups work in Arma and Altis Life is... 

It's because you weren't the leader of the group and one was missing.
It DOESN'T happen on civ becuase you're always a leader then. Go in the cop slot first that is group lead an no spam...

A Bohemia person commented on it here: https://forums.bistudio.com/topic/188354-arma3stable156134627ds-rpt-spamerrors-if-not-spawn-as-leader-in-lobby/
