### ISSUE TITLE
vehicles are not losing fuel

### ISSUE THREAD

**Issue by 9mmfullclip** [ArmaLife/Altis#510]
Hello, from testing 4.4r2 i can see that vehicles have endless fuel tanks. here is EXAMPLE code how to fix this in a very ugly way that is bad for performance (via http://www.altisliferpg.com/topic/4812-tutorial-how-to-increase-the-fuel-usage/): https://github.com/ALTISLIFERPG-XOREAXEAX-DE/Altis/commit/3a1720af348690b2b3e3512053abd6c0bf4183bf

Please test vehicle fuel in 4.4r2 and find a more elegant way to deplete it :)

**Comment by NiiRoZz** [comment]
Can't fix it's bis fault.

Cordially : NiiRoZz

**Comment by tkcjesse** [comment]
@NiiRoZz, How is it Bohemias Fault?...   I just pulled out a car and drove around and it lost fuel....

Did you even test this yourself or have some sort of proof? I suggest you pull out a car...

**Comment by NiiRoZz** [comment]
Men, this guys would just the fuel drop more rapidly because in arma the fuel it's very slow to pull Dow, so if this guys would this juste put the script in altisliferpg forum, and if you put another script, don't put it in global Altis Life please Thanks you

**Comment by tkcjesse** [comment]
@NiiRoZz He is claiming that the vehicles aren't loosing fuel... Nothing more, nothing less.

**Comment by tkcjesse** [comment]
@9mmfullclip - I was unable to reproduce the issue using the current build. Vehicle fuel does indeed decrease. If you're talking about the vehicle not coming back out with the fuel level it had, make sure you have https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/Config_Master.hpp#L18 set to true. Otherwise the vehicles will be full of fuel regardless if they were stored with 25% fuel left or 80%. 

I pulled out a sports hatch and it indeed lost fuel and saved the fuel amount properly.
https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/Config_Master.hpp#L18
