### ISSUE TITLE
players logging out when airborne are in for a big surprise

### ISSUE THREAD

**Issue by 9mmfullclip** [ArmaLife/Altis#541]
Logging out when being a passenger in a helicopter will make you spawn in 300 metres over ground, or where the helicopter was when you logged out.

Without a parachute.

Ouch.

**Comment by DarkSilencerZA** [comment]
Epic. Should keep it that way. After all, who logs out of a heli in real life. #lol

**Comment by Heavybob** [comment]
Might be a nice idea to force add parachute if above the ground

**Comment by tkcjesse** [comment]
I mean an easy fix for this would be to just save player position and not use the elevation. I don't know what to do in this case really. We could an if statement for if the elevation is over like 150m that it sets it to zero... Could cause people to spawn in rocks and stuff then though too... Idk, moral of the story is don't log in helicopters. Otherwise we could just not save elevation all together. Idk....

**Comment by danielstuart14** [comment]
just check if player is inside a vehicle when saving, and if its elevation is higher than 5, then, spawn player with a parachute.

**Comment by danielstuart14** [comment]
I can take a look on it later, we would need a new field in DB, for "in vehicle"

**Comment by tkcjesse** [comment]
@danielstuart14 or check if player is :  (vehicle player) isKindOf "Air"   then just set the elevation to zero when saving to db.. would remove the extra field.. and parachute stuff. because lets face it by the time the cutscene stops and such, chances are that person would be very close to the ground anyways. lol

**Comment by Liam0** [comment]
Thx @BoGuu seems to be working during my testing. if its not feel free to reopen the issue
